---

jobs:
- name: consul-smoke-test
  public: true
  plan:
  # - task: hello-world
  #   config:
  #     platform: linux
  #     image_resource:
  #       type: docker-image
  #       source: {repository: busybox}
  - task: concourse-smoke-test
    config:
      inputs:
      - name: pipeline
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: ./run.sh
