---
resources:
- name: resource-smoke-test
  type: git
  source:
    uri: https://github.com/jmitre/concourseSmokeTest.git

jobs:
- name: consul-smoke-test
  public: true
  plan:
  - get: resource-smoke-test
  - task: concourse-smoke-test
    file: resource-smoke-test/task.yml
  - task: run ll
    file: resource-smoke-test/runll_task.yml
